using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/B_SaveLoad")]
public partial class B_SaveLoad : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4970783720545735888,6934705596981254288));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public UnityEngine.Vector3 ResponsePoint
	{
		get
		{
			return _ResponsePoint[Entity.Index];
		}
		set
		{
			_ResponsePoint[Entity.Index] = value;
		}
	}
	public System.Boolean StageClear
	{
		get
		{
			return _StageClear[Entity.Index];
		}
		set
		{
			_StageClear[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5686335898417767566,14105588177874303420));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector3 __ResponsePoint;
	public static BansheeGz.BGDatabase.BGFieldVector3 _ResponsePoint
	{
		get
		{
			if(__ResponsePoint==null || __ResponsePoint.IsDeleted) __ResponsePoint=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(5035849836603096671,12699731003929081489));
			return __ResponsePoint;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool __StageClear;
	public static BansheeGz.BGDatabase.BGFieldBool _StageClear
	{
		get
		{
			if(__StageClear==null || __StageClear.IsDeleted) __StageClear=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(5597321103825847656,826249017324389029));
			return __StageClear;
		}
	}
}
