using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

public partial class D_Chat : BGEntity
{

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta)
		{
			return new D_Chat(meta);
		}
		public BGEntity NewEntity(BGMetaEntity meta, BGId id)
		{
			return new D_Chat(meta, id);
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5546031450402290947,16712102860754600867));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities
	{
		get
		{
			return MetaDefault.CountEntities;
		}
	}
	public System.String F_name
	{
		get
		{
			return _F_name[Index];
		}
		set
		{
			_F_name[Index] = value;
		}
	}
	public System.Int32 F_ObjNum
	{
		get
		{
			return _F_ObjNum[Index];
		}
		set
		{
			_F_ObjNum[Index] = value;
		}
	}
	public System.String F_ChatString
	{
		get
		{
			return _F_ChatString[Index];
		}
		set
		{
			_F_ChatString[Index] = value;
		}
	}
	public System.Int32 F_ChatNum
	{
		get
		{
			return _F_ChatNum[Index];
		}
		set
		{
			_F_ChatNum[Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name
	{
		get
		{
			if(_ufle12jhs77_F_name==null || _ufle12jhs77_F_name.IsDeleted) _ufle12jhs77_F_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5614771609181471789,12546016194889850768));
			return _ufle12jhs77_F_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_F_ObjNum;
	public static BansheeGz.BGDatabase.BGFieldInt _F_ObjNum
	{
		get
		{
			if(_ufle12jhs77_F_ObjNum==null || _ufle12jhs77_F_ObjNum.IsDeleted) _ufle12jhs77_F_ObjNum=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4865286558714921774,5117919433651875226));
			return _ufle12jhs77_F_ObjNum;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_F_ChatString;
	public static BansheeGz.BGDatabase.BGFieldString _F_ChatString
	{
		get
		{
			if(_ufle12jhs77_F_ChatString==null || _ufle12jhs77_F_ChatString.IsDeleted) _ufle12jhs77_F_ChatString=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5192925461702966739,13607613804958907285));
			return _ufle12jhs77_F_ChatString;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_F_ChatNum;
	public static BansheeGz.BGDatabase.BGFieldInt _F_ChatNum
	{
		get
		{
			if(_ufle12jhs77_F_ChatNum==null || _ufle12jhs77_F_ChatNum.IsDeleted) _ufle12jhs77_F_ChatNum=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(5440242012601217819,549540831188726684));
			return _ufle12jhs77_F_ChatNum;
		}
	}
	private static readonly D_Chat.Factory _factory0_PFS = new D_Chat.Factory();
	private static readonly D_SaveLoad.Factory _factory1_PFS = new D_SaveLoad.Factory();
	private static readonly D_StageData.Factory _factory2_PFS = new D_StageData.Factory();
	private static readonly D_ObjectText.Factory _factory3_PFS = new D_ObjectText.Factory();
	private D_Chat() : base(MetaDefault)
	{
	}
	private D_Chat(BGId id) : base(MetaDefault, id)
	{
	}
	private D_Chat(BGMetaEntity meta) : base(meta)
	{
	}
	private D_Chat(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static D_Chat FindEntity(Predicate<D_Chat> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((D_Chat) entity)) as D_Chat;
	}
	public static List<D_Chat> FindEntities(Predicate<D_Chat> filter, List<D_Chat> result=null, Comparison<D_Chat> sort=null)
	{
		result = result ?? new List<D_Chat>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((D_Chat) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((D_Chat) e1, (D_Chat) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((D_Chat) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<D_Chat> action, Predicate<D_Chat> filter=null, Comparison<D_Chat> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((D_Chat) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((D_Chat) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((D_Chat)e1,(D_Chat)e2));
	}
	public static D_Chat GetEntity(BGId entityId)
	{
		return (D_Chat) MetaDefault.GetEntity(entityId);
	}
	public static D_Chat GetEntity(int index)
	{
		return (D_Chat) MetaDefault[index];
	}
	public static D_Chat GetEntity(string entityName)
	{
		return (D_Chat) MetaDefault.GetEntity(entityName);
	}
	public static D_Chat NewEntity()
	{
		return (D_Chat) MetaDefault.NewEntity();
	}
}

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

public partial class D_SaveLoad : BGEntity
{

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta)
		{
			return new D_SaveLoad(meta);
		}
		public BGEntity NewEntity(BGMetaEntity meta, BGId id)
		{
			return new D_SaveLoad(meta, id);
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4970783720545735888,6934705596981254288));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities
	{
		get
		{
			return MetaDefault.CountEntities;
		}
	}
	public System.String F_name
	{
		get
		{
			return _F_name[Index];
		}
		set
		{
			_F_name[Index] = value;
		}
	}
	public UnityEngine.Vector3 F_ResponsePoint
	{
		get
		{
			return _F_ResponsePoint[Index];
		}
		set
		{
			_F_ResponsePoint[Index] = value;
		}
	}
	public System.Boolean F_StageClear
	{
		get
		{
			return _F_StageClear[Index];
		}
		set
		{
			_F_StageClear[Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name
	{
		get
		{
			if(_ufle12jhs77_F_name==null || _ufle12jhs77_F_name.IsDeleted) _ufle12jhs77_F_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5686335898417767566,14105588177874303420));
			return _ufle12jhs77_F_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_F_ResponsePoint;
	public static BansheeGz.BGDatabase.BGFieldVector3 _F_ResponsePoint
	{
		get
		{
			if(_ufle12jhs77_F_ResponsePoint==null || _ufle12jhs77_F_ResponsePoint.IsDeleted) _ufle12jhs77_F_ResponsePoint=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(5035849836603096671,12699731003929081489));
			return _ufle12jhs77_F_ResponsePoint;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_F_StageClear;
	public static BansheeGz.BGDatabase.BGFieldBool _F_StageClear
	{
		get
		{
			if(_ufle12jhs77_F_StageClear==null || _ufle12jhs77_F_StageClear.IsDeleted) _ufle12jhs77_F_StageClear=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(5597321103825847656,826249017324389029));
			return _ufle12jhs77_F_StageClear;
		}
	}
	private static readonly D_Chat.Factory _factory0_PFS = new D_Chat.Factory();
	private static readonly D_SaveLoad.Factory _factory1_PFS = new D_SaveLoad.Factory();
	private static readonly D_StageData.Factory _factory2_PFS = new D_StageData.Factory();
	private static readonly D_ObjectText.Factory _factory3_PFS = new D_ObjectText.Factory();
	private D_SaveLoad() : base(MetaDefault)
	{
	}
	private D_SaveLoad(BGId id) : base(MetaDefault, id)
	{
	}
	private D_SaveLoad(BGMetaEntity meta) : base(meta)
	{
	}
	private D_SaveLoad(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static D_SaveLoad FindEntity(Predicate<D_SaveLoad> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((D_SaveLoad) entity)) as D_SaveLoad;
	}
	public static List<D_SaveLoad> FindEntities(Predicate<D_SaveLoad> filter, List<D_SaveLoad> result=null, Comparison<D_SaveLoad> sort=null)
	{
		result = result ?? new List<D_SaveLoad>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((D_SaveLoad) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((D_SaveLoad) e1, (D_SaveLoad) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((D_SaveLoad) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<D_SaveLoad> action, Predicate<D_SaveLoad> filter=null, Comparison<D_SaveLoad> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((D_SaveLoad) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((D_SaveLoad) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((D_SaveLoad)e1,(D_SaveLoad)e2));
	}
	public static D_SaveLoad GetEntity(BGId entityId)
	{
		return (D_SaveLoad) MetaDefault.GetEntity(entityId);
	}
	public static D_SaveLoad GetEntity(int index)
	{
		return (D_SaveLoad) MetaDefault[index];
	}
	public static D_SaveLoad GetEntity(string entityName)
	{
		return (D_SaveLoad) MetaDefault.GetEntity(entityName);
	}
	public static D_SaveLoad NewEntity()
	{
		return (D_SaveLoad) MetaDefault.NewEntity();
	}
}

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

public partial class D_StageData : BGEntity
{

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta)
		{
			return new D_StageData(meta);
		}
		public BGEntity NewEntity(BGMetaEntity meta, BGId id)
		{
			return new D_StageData(meta, id);
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4616669881433414317,999969829826134704));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities
	{
		get
		{
			return MetaDefault.CountEntities;
		}
	}
	public System.String F_name
	{
		get
		{
			return _F_name[Index];
		}
		set
		{
			_F_name[Index] = value;
		}
	}
	public UnityEngine.Vector3 F_ResponsePosition
	{
		get
		{
			return _F_ResponsePosition[Index];
		}
		set
		{
			_F_ResponsePosition[Index] = value;
		}
	}
	public UnityEngine.Quaternion F_ResponseRotation
	{
		get
		{
			return _F_ResponseRotation[Index];
		}
		set
		{
			_F_ResponseRotation[Index] = value;
		}
	}
	public System.Boolean F_StageClear
	{
		get
		{
			return _F_StageClear[Index];
		}
		set
		{
			_F_StageClear[Index] = value;
		}
	}
	public UnityEngine.Vector3 F_StagePosition
	{
		get
		{
			return _F_StagePosition[Index];
		}
		set
		{
			_F_StagePosition[Index] = value;
		}
	}
	public UnityEngine.Quaternion F_StageRotation
	{
		get
		{
			return _F_StageRotation[Index];
		}
		set
		{
			_F_StageRotation[Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name
	{
		get
		{
			if(_ufle12jhs77_F_name==null || _ufle12jhs77_F_name.IsDeleted) _ufle12jhs77_F_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5319597434205999055,12568856221011576477));
			return _ufle12jhs77_F_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_F_ResponsePosition;
	public static BansheeGz.BGDatabase.BGFieldVector3 _F_ResponsePosition
	{
		get
		{
			if(_ufle12jhs77_F_ResponsePosition==null || _ufle12jhs77_F_ResponsePosition.IsDeleted) _ufle12jhs77_F_ResponsePosition=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4778463960804466034,5786887131447245965));
			return _ufle12jhs77_F_ResponsePosition;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_F_ResponseRotation;
	public static BansheeGz.BGDatabase.BGFieldQuaternion _F_ResponseRotation
	{
		get
		{
			if(_ufle12jhs77_F_ResponseRotation==null || _ufle12jhs77_F_ResponseRotation.IsDeleted) _ufle12jhs77_F_ResponseRotation=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(5079607956534320973,15847534016968931209));
			return _ufle12jhs77_F_ResponseRotation;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_F_StageClear;
	public static BansheeGz.BGDatabase.BGFieldBool _F_StageClear
	{
		get
		{
			if(_ufle12jhs77_F_StageClear==null || _ufle12jhs77_F_StageClear.IsDeleted) _ufle12jhs77_F_StageClear=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(5024408334515454238,6020562075830421135));
			return _ufle12jhs77_F_StageClear;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_F_StagePosition;
	public static BansheeGz.BGDatabase.BGFieldVector3 _F_StagePosition
	{
		get
		{
			if(_ufle12jhs77_F_StagePosition==null || _ufle12jhs77_F_StagePosition.IsDeleted) _ufle12jhs77_F_StagePosition=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(4789782483200644650,16797022101096301186));
			return _ufle12jhs77_F_StagePosition;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldQuaternion _ufle12jhs77_F_StageRotation;
	public static BansheeGz.BGDatabase.BGFieldQuaternion _F_StageRotation
	{
		get
		{
			if(_ufle12jhs77_F_StageRotation==null || _ufle12jhs77_F_StageRotation.IsDeleted) _ufle12jhs77_F_StageRotation=(BansheeGz.BGDatabase.BGFieldQuaternion) MetaDefault.GetField(new BGId(4927286363862233345,15134226064723963528));
			return _ufle12jhs77_F_StageRotation;
		}
	}
	private static readonly D_Chat.Factory _factory0_PFS = new D_Chat.Factory();
	private static readonly D_SaveLoad.Factory _factory1_PFS = new D_SaveLoad.Factory();
	private static readonly D_StageData.Factory _factory2_PFS = new D_StageData.Factory();
	private static readonly D_ObjectText.Factory _factory3_PFS = new D_ObjectText.Factory();
	private D_StageData() : base(MetaDefault)
	{
	}
	private D_StageData(BGId id) : base(MetaDefault, id)
	{
	}
	private D_StageData(BGMetaEntity meta) : base(meta)
	{
	}
	private D_StageData(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static D_StageData FindEntity(Predicate<D_StageData> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((D_StageData) entity)) as D_StageData;
	}
	public static List<D_StageData> FindEntities(Predicate<D_StageData> filter, List<D_StageData> result=null, Comparison<D_StageData> sort=null)
	{
		result = result ?? new List<D_StageData>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((D_StageData) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((D_StageData) e1, (D_StageData) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((D_StageData) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<D_StageData> action, Predicate<D_StageData> filter=null, Comparison<D_StageData> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((D_StageData) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((D_StageData) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((D_StageData)e1,(D_StageData)e2));
	}
	public static D_StageData GetEntity(BGId entityId)
	{
		return (D_StageData) MetaDefault.GetEntity(entityId);
	}
	public static D_StageData GetEntity(int index)
	{
		return (D_StageData) MetaDefault[index];
	}
	public static D_StageData GetEntity(string entityName)
	{
		return (D_StageData) MetaDefault.GetEntity(entityName);
	}
	public static D_StageData NewEntity()
	{
		return (D_StageData) MetaDefault.NewEntity();
	}
}

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

public partial class D_ObjectText : BGEntity
{

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta)
		{
			return new D_ObjectText(meta);
		}
		public BGEntity NewEntity(BGMetaEntity meta, BGId id)
		{
			return new D_ObjectText(meta, id);
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5614948582434125714,9141248852051960742));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities
	{
		get
		{
			return MetaDefault.CountEntities;
		}
	}
	public System.String F_name
	{
		get
		{
			return _F_name[Index];
		}
		set
		{
			_F_name[Index] = value;
		}
	}
	public System.Collections.Hashtable F_Test
	{
		get
		{
			return _F_Test[Index];
		}
		set
		{
			_F_Test[Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name
	{
		get
		{
			if(_ufle12jhs77_F_name==null || _ufle12jhs77_F_name.IsDeleted) _ufle12jhs77_F_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5120082738648672254,1397212341766930332));
			return _ufle12jhs77_F_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldHashtable _ufle12jhs77_F_Test;
	public static BansheeGz.BGDatabase.BGFieldHashtable _F_Test
	{
		get
		{
			if(_ufle12jhs77_F_Test==null || _ufle12jhs77_F_Test.IsDeleted) _ufle12jhs77_F_Test=(BansheeGz.BGDatabase.BGFieldHashtable) MetaDefault.GetField(new BGId(5336635941771384359,10414727297182596287));
			return _ufle12jhs77_F_Test;
		}
	}
	private static readonly D_Chat.Factory _factory0_PFS = new D_Chat.Factory();
	private static readonly D_SaveLoad.Factory _factory1_PFS = new D_SaveLoad.Factory();
	private static readonly D_StageData.Factory _factory2_PFS = new D_StageData.Factory();
	private static readonly D_ObjectText.Factory _factory3_PFS = new D_ObjectText.Factory();
	private D_ObjectText() : base(MetaDefault)
	{
	}
	private D_ObjectText(BGId id) : base(MetaDefault, id)
	{
	}
	private D_ObjectText(BGMetaEntity meta) : base(meta)
	{
	}
	private D_ObjectText(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static D_ObjectText FindEntity(Predicate<D_ObjectText> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((D_ObjectText) entity)) as D_ObjectText;
	}
	public static List<D_ObjectText> FindEntities(Predicate<D_ObjectText> filter, List<D_ObjectText> result=null, Comparison<D_ObjectText> sort=null)
	{
		result = result ?? new List<D_ObjectText>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((D_ObjectText) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((D_ObjectText) e1, (D_ObjectText) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((D_ObjectText) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<D_ObjectText> action, Predicate<D_ObjectText> filter=null, Comparison<D_ObjectText> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((D_ObjectText) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((D_ObjectText) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((D_ObjectText)e1,(D_ObjectText)e2));
	}
	public static D_ObjectText GetEntity(BGId entityId)
	{
		return (D_ObjectText) MetaDefault.GetEntity(entityId);
	}
	public static D_ObjectText GetEntity(int index)
	{
		return (D_ObjectText) MetaDefault[index];
	}
	public static D_ObjectText GetEntity(string entityName)
	{
		return (D_ObjectText) MetaDefault.GetEntity(entityName);
	}
	public static D_ObjectText NewEntity()
	{
		return (D_ObjectText) MetaDefault.NewEntity();
	}
}
#pragma warning restore 414
