using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

public partial class D_SaveLoad : BGEntity
{

	//=============================================================
	//||                   Generated by BansheeGz Code Generator ||
	//=============================================================

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta)
		{
			return new D_SaveLoad(meta);
		}
		public BGEntity NewEntity(BGMetaEntity meta, BGId id)
		{
			return new D_SaveLoad(meta, id);
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4970783720545735888,6934705596981254288));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
	public static int CountEntities
	{
		get
		{
			return MetaDefault.CountEntities;
		}
	}
	public System.String F_name
	{
		get
		{
			return _F_name[Index];
		}
		set
		{
			_F_name[Index] = value;
		}
	}
	public UnityEngine.Vector3 F_ResponsePoint
	{
		get
		{
			return _F_ResponsePoint[Index];
		}
		set
		{
			_F_ResponsePoint[Index] = value;
		}
	}
	public System.Boolean F_StageClear
	{
		get
		{
			return _F_StageClear[Index];
		}
		set
		{
			_F_StageClear[Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_F_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _F_name
	{
		get
		{
			if(_ufle12jhs77_F_name==null || _ufle12jhs77_F_name.IsDeleted) _ufle12jhs77_F_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5686335898417767566,14105588177874303420));
			return _ufle12jhs77_F_name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldVector3 _ufle12jhs77_F_ResponsePoint;
	public static BansheeGz.BGDatabase.BGFieldVector3 _F_ResponsePoint
	{
		get
		{
			if(_ufle12jhs77_F_ResponsePoint==null || _ufle12jhs77_F_ResponsePoint.IsDeleted) _ufle12jhs77_F_ResponsePoint=(BansheeGz.BGDatabase.BGFieldVector3) MetaDefault.GetField(new BGId(5035849836603096671,12699731003929081489));
			return _ufle12jhs77_F_ResponsePoint;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_F_StageClear;
	public static BansheeGz.BGDatabase.BGFieldBool _F_StageClear
	{
		get
		{
			if(_ufle12jhs77_F_StageClear==null || _ufle12jhs77_F_StageClear.IsDeleted) _ufle12jhs77_F_StageClear=(BansheeGz.BGDatabase.BGFieldBool) MetaDefault.GetField(new BGId(5597321103825847656,826249017324389029));
			return _ufle12jhs77_F_StageClear;
		}
	}
	private static readonly D_SaveLoad.Factory _factory0_PFS = new D_SaveLoad.Factory();
	private D_SaveLoad() : base(MetaDefault)
	{
	}
	private D_SaveLoad(BGId id) : base(MetaDefault, id)
	{
	}
	private D_SaveLoad(BGMetaEntity meta) : base(meta)
	{
	}
	private D_SaveLoad(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static D_SaveLoad FindEntity(Predicate<D_SaveLoad> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((D_SaveLoad) entity)) as D_SaveLoad;
	}
	public static List<D_SaveLoad> FindEntities(Predicate<D_SaveLoad> filter, List<D_SaveLoad> result=null, Comparison<D_SaveLoad> sort=null)
	{
		result = result ?? new List<D_SaveLoad>();
		_find_Entities_Result.Clear();
		MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((D_SaveLoad) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((D_SaveLoad) e1, (D_SaveLoad) e2));
		if (_find_Entities_Result.Count != 0)
		{
			for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((D_SaveLoad) _find_Entities_Result[i]);
			_find_Entities_Result.Clear();
		}
		return result;
	}
	public static void ForEachEntity(Action<D_SaveLoad> action, Predicate<D_SaveLoad> filter=null, Comparison<D_SaveLoad> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((D_SaveLoad) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((D_SaveLoad) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((D_SaveLoad)e1,(D_SaveLoad)e2));
	}
	public static D_SaveLoad GetEntity(BGId entityId)
	{
		return (D_SaveLoad) MetaDefault.GetEntity(entityId);
	}
	public static D_SaveLoad GetEntity(int index)
	{
		return (D_SaveLoad) MetaDefault[index];
	}
	public static D_SaveLoad GetEntity(string entityName)
	{
		return (D_SaveLoad) MetaDefault.GetEntity(entityName);
	}
	public static D_SaveLoad NewEntity()
	{
		return (D_SaveLoad) MetaDefault.NewEntity();
	}
}
#pragma warning restore 414
