using System;
using System.Collections.Generic;
using UnityEngine;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

[AddComponentMenu("BansheeGz/Generated/B_ObjectText")]
public partial class B_ObjectText : BGEntityGo
{
	public override BGMetaEntity MetaConstraint
	{
		get
		{
			return MetaDefault;
		}
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
	{
		get
		{
			if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5614948582434125714,9141248852051960742));
			return _metaDefault;
		}
	}
	public static BansheeGz.BGDatabase.BGRepoEvents Events
	{
		get
		{
			return BGRepo.I.Events;
		}
	}
	public new System.String name
	{
		get
		{
			return _name[Entity.Index];
		}
		set
		{
			_name[Entity.Index] = value;
		}
	}
	public System.Collections.Hashtable Test
	{
		get
		{
			return _Test[Entity.Index];
		}
		set
		{
			_Test[Entity.Index] = value;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName __name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name
	{
		get
		{
			if(__name==null || __name.IsDeleted) __name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5120082738648672254,1397212341766930332));
			return __name;
		}
	}
	private static BansheeGz.BGDatabase.BGFieldHashtable __Test;
	public static BansheeGz.BGDatabase.BGFieldHashtable _Test
	{
		get
		{
			if(__Test==null || __Test.IsDeleted) __Test=(BansheeGz.BGDatabase.BGFieldHashtable) MetaDefault.GetField(new BGId(5336635941771384359,10414727297182596287));
			return __Test;
		}
	}
}
